### ISSUE TITLE
Python3: ModuleNotFoundError: No module named 'PIL' | 个人博客

### ISSUE THREAD

**Issue by tanjuntao** [tanjuntao/tanjuntao.github.io#13]
https://tanjuntao.github.io/2019/04/02/Python3-ModuleNotFoundError-No-module-named-PIL/ 

 问题使用matplotlib.pyplot模块调用绘图函数时，出现以上错误。 解决方法在控制台中输入如下命令1pip install pillow 即可解决问题

**Comment by tanjuntao101** [comment]
hahaha终于成功了。就是之前一些文章没办法跳转。
